### ISSUE TITLE
Failing examples after PR #89 (glbinding)

### ISSUE THREAD

**Issue by shehzan10** [arrayfire/forge#102]
- [x] Bubblecart, field and stream need to be written for CUDA and OpenCL
- [x] There might be a bug in `plotting` that occasionally colors the yellow lines as blue and sometimes shows gaps in the lines (Linux + NVIDIA)
- [x] Surface OpenCL doesn't render the surface (Linux + NVIDIA)
- [x] Plotting CUDA fails on TX1 with unknown CUDA error on line 69 of plotting.cu
- [x] Histogram examples on TX1 sometimes do not render the histogram.
- [x] One OSX, surface and plot3 examples fail on CPU and OpenCL with errors similar to:
```
jesse:build jenkins-slave$ ./examples/cpu/plot3_cpu 
InfoLog:
WARNING: Output of vertex shader 'hpoint' not read by fragment shader

libc++abi.dylib: terminating with uncaught exception of type forge::Error: OpenGL Shader linking failed
Abort trap: 6
```

**Comment by pavanky** [comment]
maximizing fractal, bubblechart, field examples on cpu seem to be causing the following error:

```
Failed to blit
Segmentation fault (core dumped)
```

**Comment by pavanky** [comment]
The above error only seems to happen when using Intel graphics but works when using nvidia GPU

**Comment by shehzan10** [comment]
Errors from the issue message fixed in devel.
@pavanky can you check the error you reported with the latest devel?

**Comment by 9prady9** [comment]
fyi - I am working on adding the examples for left over backends.

**Comment by 9prady9** [comment]
@shehzan10 Is this `There might be a bug in plotting that occasionally colors the yellow lines as blue and sometimes shows gaps in the lines (Linux + NVIDIA)` resolved ? what was the issue ?

**Comment by shehzan10** [comment]
Yes this was resolved. Except for the resize issue @pavanky talks about, there seem to be no other issues across all platforms.

**Comment by pavanky** [comment]
I think we can safely ignore the resize issue.

That said AMD is still broken (but it is referenced in another issue).

**Comment by FloopCZ** [comment]
I am not sure whether this issue has been resolved or it was not worth the effort, but I am suffering from the same issue as @pavanky on CPU and OpenCL backends (have not tried CUDA yet). When I resize a window, the application crashes with:
```
Failed to blit
[1]    27708 segmentation fault (core dumped)
```
By the way, is there a way to zoom the canvas? The plot can be shifted and rotated with left and right mouse respectively, but was not able to zoom in or out.

**Comment by 9prady9** [comment]
@FloopCZ Which GPU are you using this on ?

"ALT+Left Click" and move mouse up/down to zoom in/out. On a mouse pad, move a second finger up/down while the left click and alt are held pressed.

**Comment by FloopCZ** [comment]
@9prady9 Thank you for the answer, I have filled a separate issue #152 for this.
