### ISSUE TITLE
osx build issues

### ISSUE THREAD

**Issue by tmpvar** [arrayfire/forge#58]
On OSX El Capitan (10.11)
Using cmake@3.3.2
and clang:
```
forge (master)‣ clang --version
Apple LLVM version 7.0.0 (clang-700.1.76)
Target: x86_64-apple-darwin15.0.0
Thread model: posix
```

after cloning forge and [running through the build process](https://gist.githubusercontent.com/tmpvar/833d462b3774f1199348/raw/9dd6f6bf9ea83a72cbceb7c9a9e868fe92052105/clone%2520and%2520build)

I'm seeing

```
[ 69%] Building CXX object examples/CMakeFiles/example_histogram_opencl.dir/opencl/histogram.cpp.o
/Users/tmpvar/work/gfx/tmp/forge/examples/opencl/histogram.cpp:283:16: error: use of undeclared identifier 'fmod'
            if(fmod(persistance, 0.5f) < 0.01)
               ^
1 error generated.
```

after applying [this patch](https://gist.githubusercontent.com/tmpvar/833d462b3774f1199348/raw/9dd6f6bf9ea83a72cbceb7c9a9e868fe92052105/add-math.h.patch)

I was able to get it to build, but upon running the `surface_opencl` demo I see:

```
forge (master)‣ examples/opencl/surface_opencl
InfoLog:
WARNING: Output of vertex shader 'hpoint' not read by fragment shader

OpenGL Shader linking failed(2001)
```

**Comment by 9prady9** [comment]
Fixed with the commit 823b00b38b7f10dbe7b6469ae60ebf9c11391fde. The fixes are in master now.

**Comment by tmpvar** [comment]
looks like there is still an issue, everything builds as expected (thanks!) but running any of the opencl examples results in a flash and then the process terminates

![opencl examples fail to run](https://cloud.githubusercontent.com/assets/46673/10856931/6463928c-7f21-11e5-89e0-876e690f292e.gif)

**Comment by 9prady9** [comment]
Do you happen to have a CUDA device by any chance ? If so, can you please check the example on CUDA example and let us even if that is failing or not. Thank you.

**Comment by tmpvar** [comment]
I do not as I'm running an `AMD Radeon R9 M370X 2048 MB` on a `MacBook Pro (Retina, 15-inch, Mid 2015)`

**Comment by tmpvar** [comment]
I stepped through and it looks like it fails at `getPlatform` -- all of the platforms returned are labeled "Apple"

**Comment by 9prady9** [comment]
Hm, that is probably the reason then. I will fix this on all examples and update the issue as soon as it is done. Thanks for tracking it down.

**Comment by tmpvar** [comment]
patched with 

```diff
diff --git a/examples/opencl/cl_helpers.h b/examples/opencl/cl_helpers.h
index 58fa1cb..04ed1c7 100644
--- a/examples/opencl/cl_helpers.h
+++ b/examples/opencl/cl_helpers.h
@@ -16,6 +16,7 @@ using namespace cl;
 static const std::string NVIDIA_PLATFORM = "NVIDIA CUDA";
 static const std::string AMD_PLATFORM = "AMD Accelerated Parallel Processing";
 static const std::string INTEL_PLATFORM = "Intel(R) OpenCL";
+static const std::string APPLE_PLATFORM = "Apple";
 
 #if defined (OS_MAC)
 static const std::string CL_GL_SHARING_EXT = "cl_APPLE_gl_sharing";
@@ -65,7 +66,12 @@ Platform getPlatform()
         if (errCode != CL_SUCCESS) {
             Platform plat = getPlatform(INTEL_PLATFORM, errCode);
             if (errCode != CL_SUCCESS) {
-                exit(255);
+                Platform plat = getPlatform(APPLE_PLATFORM, errCode);
+                if (errCode != CL_SUCCESS) {
+                    exit(255);
+                } else {
+                    return plat;
+                }
             } else
                 return plat;
         } else
```

and it gets a bit further:

```
Found platform: Apple
clCreateCommandQueue(-33)
Program ended with exit code: 0
```

**Comment by 9prady9** [comment]
That is an invalid device error code, can you trying printing the device info in [this](https://github.com/arrayfire/forge/blob/master/examples/opencl/fractal.cpp#L168) line and see what does it print.

**Comment by tmpvar** [comment]
```
Found platform: Apple
device name: Iris Pro
opencl version: OpenCL C 1.2 
max compute units: 40
local mem size: 65536
```
and if I remove the break from that loop

```
Found platform: Apple
device name: Iris Pro
opencl version: OpenCL C 1.2 
max compute units: 40
local mem size: 65536
device name: AMD Radeon R9 M370X Compute Engine
opencl version: OpenCL C 1.2 
max compute units: 10
local mem size: 32768
```

and then the example runs! So it looks like we should filter based on command queue capability

**Comment by 9prady9** [comment]
If the `checkExtnAvailability` is returning true, it should run on Intel integrated GPU as well. It is odd that it isn't. Having said that, i never had a good experience with Intel OpenCL either on linux or Windows so far. Are you able to run any other opencl related programs on Intel device ? Just curious if it is just our examples or all opencl programs on intel device.

**Comment by 9prady9** [comment]
@tmpvar I have fixed the opencl fractal example now. Can you please latest master and let me know if  fractal is running fine for you.

**Comment by tmpvar** [comment]
will do this evening

**Comment by tmpvar** [comment]
@9prady9 looks good, thanks!
